apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      tier: app
  template:
    metadata:
      labels:
        app: hello
        tier: app
    spec:
      containers:
        - name: hello
          image: docker.io/moochi/hello:latest
